site_domain: staging.kakitube.com
imdb_api: 5648389e
google_analytics_tracker: UA-60500928-1
fb_app_id: 367753823253755
s3:
  bucket: kakitube-staging
  region: ap-southeast-1
image_host: https://kakitube-staging.s3.amazonaws.com
redis:
  server: localhost
  namespace: kakitube_staging